"""
KrystalOS — cli/commands/make_widget.py
`krystal make:widget` — interactive wizard to scaffold a new widget.
"""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent

import typer
from jinja2 import Environment, FileSystemLoader
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, IntPrompt
from rich.table import Table

from core.schema import KrystalWidget, SupportedLanguage, Runtime, UI, GridSize, Capabilities, Modes
from shared.utils import ensure_krystal_project

console = Console()

# Starter templates keyed by language
_STARTERS: dict[str, tuple[str, str]] = {
    "python": ("index.py", dedent("""\
        # KrystalOS Widget — {name}
        # Runtime: Python {lang_version}
        # Auto-generated by krystal make:widget
        
        def main():
            print("Hello from widget: {name}")
        
        if __name__ == "__main__":
            main()
    """)),
    "php": ("index.php", dedent("""\
        <?php
        // KrystalOS Widget — {name}
        // Runtime: PHP {lang_version}
        // Auto-generated by krystal make:widget
        
        echo "Hello from widget: {name}";
    """)),
    # PATCH 3: 'javascript' key added — was missing, causing JS→Java off-by-one.
    "javascript": ("index.js", dedent("""\
        // KrystalOS Widget — {name}
        // Runtime: Node {lang_version}
        // Auto-generated by krystal make:widget
        
        console.log("Hello from widget: {name}");
    """)),
    "js": ("index.js", dedent("""\
        // KrystalOS Widget — {name}
        // Runtime: Node {lang_version}
        // Auto-generated by krystal make:widget
        
        console.log("Hello from widget: {name}");
    """)),
    "node": ("index.js", dedent("""\
        // KrystalOS Widget — {name}
        // Runtime: Node {lang_version}
        // Auto-generated by krystal make:widget
        
        console.log("Hello from widget: {name}");
    """)),
    "typescript": ("index.ts", dedent("""\
        // KrystalOS Widget — {name}
        // Runtime: Node/TypeScript {lang_version}
        // Auto-generated by krystal make:widget
        
        const msg: string = 'Hello from widget: {name}';
        console.log(msg);
    """)),
}


def _ui_html(widget_name: str, theme_color: str) -> str:
    """Generate a Tailwind Glassmorphism base ui.html for the widget."""
    return dedent(f"""\
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>{widget_name} — KrystalOS Widget</title>
          <script src="https://cdn.tailwindcss.com"></script>
          <style>
            :root {{ --accent: {theme_color}; }}
            body {{
              background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
              min-height: 100vh;
              display: flex;
              align-items: center;
              justify-content: center;
              font-family: 'Inter', sans-serif;
            }}
            .glass {{
              background: rgba(255, 255, 255, 0.08);
              backdrop-filter: blur(16px);
              -webkit-backdrop-filter: blur(16px);
              border: 1px solid rgba(255, 255, 255, 0.15);
              box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
            }}
          </style>
        </head>
        <body class="text-white">
          <!-- KrystalOS Bento Widget: {widget_name} -->
          <div class="glass rounded-2xl p-6 w-72 flex flex-col gap-4">
            <div class="flex items-center gap-3">
              <span class="text-3xl">🔷</span>
              <div>
                <h1 class="text-lg font-bold tracking-tight">{widget_name}</h1>
                <p class="text-xs text-white/50">KrystalOS Widget</p>
              </div>
            </div>
            <div class="rounded-xl p-4 text-sm text-white/70"
                 style="background: rgba(255,255,255,0.05);">
              Widget content renders here.
            </div>
            <button
              class="w-full py-2 rounded-lg text-sm font-semibold transition-all
                     hover:opacity-90 active:scale-95"
              style="background: {theme_color};">
              Launch Widget
            </button>
          </div>
          <script>
            // Phase 3 hook — subscribe to KrystalOS Event Bus
            // window.__krystal?.subscribe("theme:change", (payload) => {{ ... }});
          </script>
        </body>
        </html>
    """)


def make_widget(name: str | None = None) -> None:
    """Interactive wizard to create a new KrystalOS widget.
    
    PATCH 2: Accepts an optional pre-supplied name to skip the name prompt.
    Usage: krystal make:widget           → fully interactive
           krystal make:widget MyWidget  → skips name question
    """

    console.print("\n[bold cyan]🔷 KrystalOS[/] — Widget Generator\n")

    # --- Gather input ---
    # PATCH 2: Use the pre-supplied name if provided, otherwise ask interactively.
    if name:
        name = name.strip().lower().replace(" ", "-")
        console.print(f"[dim]Nombre del widget: [cyan]{name}[/][/]")
    else:
        name = Prompt.ask("[bold]Widget name[/] (kebab-case)").strip().lower().replace(" ", "-")
    author = Prompt.ask("[bold]Author[/]").strip()

    lang_choices = "/".join(e.value for e in SupportedLanguage)
    language = Prompt.ask(
        f"[bold]Language[/] ({lang_choices})",
        choices=[e.value for e in SupportedLanguage],
        default="python",
    )
    lang_version = Prompt.ask(
        f"[bold]Runtime version[/] (e.g. 3.11, 8.2)",
        default="3.11",
    ).strip()
    w = IntPrompt.ask("[bold]Grid width[/]  (columns, 1-12)", default=2)
    h = IntPrompt.ask("[bold]Grid height[/] (rows,    1-12)", default=2)
    theme_color = Prompt.ask("[bold]Theme color[/] (hex)", default="#7C3AED").strip()

    # --- Validate via Pydantic ---
    try:
        manifest = KrystalWidget(
            name=name,
            version="0.1.0",
            author=author,
            runtime=Runtime(language=language, version=lang_version),
            ui=UI(grid_size=GridSize(w=w, h=h), icon="🔷", theme_color=theme_color),
            capabilities=Capabilities(),
            modes=Modes(native=True, docker=False),
        )
    except Exception as exc:
        console.print(f"[bold red]✗ Validation error:[/] {exc}")
        raise typer.Exit(code=1)

    # --- Resolve project root ---
    try:
        project_root = ensure_krystal_project()
    except FileNotFoundError:
        # Fall back to cwd if not inside a project (useful during development)
        project_root = Path.cwd()
        console.print(
            "[yellow]⚠[/]  No krystal.config.json found — writing widget to current directory.\n"
        )

    widget_dir = project_root / "widgets" / name
    if widget_dir.exists():
        console.print(f"[bold red]✗[/] Widget [yellow]{name}[/] already exists at {widget_dir}")
        raise typer.Exit(code=1)

    widget_dir.mkdir(parents=True)

    # krystal.json
    (widget_dir / "krystal.json").write_text(
        json.dumps(manifest.to_krystal_json(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    # Language starter file
    filename, template = _STARTERS.get(language, ("index.txt", "# {name}"))
    (widget_dir / filename).write_text(
        template.format(name=name, lang_version=lang_version),
        encoding="utf-8",
    )

    # ui.html (Tailwind Glassmorphism)
    (widget_dir / "ui.html").write_text(
        _ui_html(name, theme_color),
        encoding="utf-8",
    )

    # Document Generator (README.md)
    try:
        env = Environment(loader=FileSystemLoader(str(project_root / "templates")))
        readme_template = env.get_template("widget_readme.md")
        # model_dump() gets the dictionary representation
        rendered_readme = readme_template.render(**manifest.model_dump())
        (widget_dir / "README.md").write_text(rendered_readme, encoding="utf-8")
        readme_str = "\n  [green]•[/] README.md"
    except Exception as e:
        console.print(f"[yellow]⚠ Failed to auto-generate README.md:[/] {e}")
        readme_str = ""

    # --- Summary table ---
    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column(style="dim")
    table.add_column(style="bold white")
    table.add_row("Name", name)
    table.add_row("Language", f"{language} {lang_version}")
    table.add_row("Grid", f"{w}×{h}")
    table.add_row("Color", theme_color)
    table.add_row("Path", str(widget_dir))

    console.print(
        Panel(
            table,
            title="[bold cyan]🔷 Widget Created[/]",
            border_style="cyan",
        )
    )
    console.print(
        f"\n  [dim]Files generated:[/]\n"
        f"  [green]•[/] krystal.json\n"
        f"  [green]•[/] {filename}\n"
        f"  [green]•[/] ui.html{readme_str}\n"
    )
